// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function CreateInterface(arg1:string,arg2:string):Promise<string>;

export function DeleteInterface(arg1:string):Promise<string>;

export function Println(arg1:string):Promise<void>;

export function RegisterModels():Promise<network.HardwareInterface>;

export function UpdateInterface(arg1:network.UpdatePayload):Promise<string>;
