// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateInterface(arg1, arg2) {
  return window['go']['main']['App']['CreateInterface'](arg1, arg2);
}

export function DeleteInterface(arg1) {
  return window['go']['main']['App']['DeleteInterface'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableParsers() {
  return window['go']['main']['App']['GetAvailableParsers']();
}

export function GetWatcherState() {
  return window['go']['main']['App']['GetWatcherState']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function RegisterModels() {
  return window['go']['main']['App']['RegisterModels']();
}

export function RegisterUDPPacket() {
  return window['go']['main']['App']['RegisterUDPPacket']();
}

export function SaveWatcherConfig(arg1) {
  return window['go']['main']['App']['SaveWatcherConfig'](arg1);
}

export function StartPing(arg1, arg2) {
  return window['go']['main']['App']['StartPing'](arg1, arg2);
}

export function StartWatcher() {
  return window['go']['main']['App']['StartWatcher']();
}

export function StopPing() {
  return window['go']['main']['App']['StopPing']();
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function UpdateInterface(arg1) {
  return window['go']['main']['App']['UpdateInterface'](arg1);
}
