// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {network} from '../models';

export function CheckUpdate():Promise<services.ReleaseInfo>;

export function CreateInterface(arg1:string,arg2:string):Promise<string>;

export function DeleteInterface(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function InstallUpdate(arg1:services.ReleaseInfo):Promise<string>;

export function RegisterModels():Promise<network.HardwareInterface>;

export function StartPing(arg1:string,arg2:number):Promise<string>;

export function StopPing():Promise<void>;

export function UpdateInterface(arg1:network.UpdatePayload):Promise<string>;
