// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInterface(arg1, arg2) {
  return window['go']['main']['App']['CreateInterface'](arg1, arg2);
}

export function DeleteInterface(arg1) {
  return window['go']['main']['App']['DeleteInterface'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function RegisterModels() {
  return window['go']['main']['App']['RegisterModels']();
}

export function UpdateInterface(arg1) {
  return window['go']['main']['App']['UpdateInterface'](arg1);
}
